#ifndef _SPRITES_H_
#define _SPRITES_H_

#include <stddef.h>

// needs the typedef xpm_row_t
#include <lcom/xpm.h>

/** @defgroup sprites sprites
 * @{
 *
 * Set of pixmaps.
 */

/** Format of a xpm-like (there is a real xpm format) pic:
 * <pre>
 * static xpm_row_t const picture_name[] = {
 * "number_of_x_pixels number_of_y_pixels number_of_colors",
 * "one_char_symbol the_char_symbol_color",
 * ... exactly number_of_colors lines as above
 * "any of the above one_char_symbol, exactly number_of_x_pixels times",
 * ... exactly number_of_y_pixels lines as above
 * };
 *
 * Example:
 *
 * static xpm_row_t const pic1[] = {   // the name of the picture, "pic1" in
 * this case "32 13 4",                          // number of pixels in the x
 * and y dimension, and the number of colors, which follows.
 * ". 0",                              // mapping between symbols and colors; in
 * this case, the "." will be mapped to color 0 "x 2", // and the "x" to color 2
 * ...                                 // the next symbol/color pairs
 * "................................", // first row, exactly 32 pixels,
 *                                        all color 0, BLACK
 * "..............xxx...............", // next row has three GREEN pixels
 *                                        at the center
 * </pre>
 * Any real xpm picture can be read, as long as there are only 16
 * colors on it, and the colors are the ones available by default.
 *
 *  To use other/more colors than the basic ones, the graphic card
 *  palette must be programmed.
 *
 */


static xpm_row_t const sprite_9[] = {
    "40 31 2",
    "  0",
    "x 1",
    "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    " xxxxxxxxx                    xxxxxxxxx ",
    " xxxxxxxxx                    xxxxxxxxx ",
    " xxxxxxxxx                    xxxxxxxxx ",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
    "                               xxxxxxxx ",
    "                               xxxxxxxxx",
    "                               xxxxxxxxx",
    "                               xxxxxxxxx",
    "xxxxxxxx                       xxxxxxxxx",
    "xxxxxxxxx                      xxxxxxxxx",
    "xxxxxxxxx                      xxxxxxxxx",
    "xxxxxxxxxx                     xxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxxx                 xxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
};

static xpm_row_t const sprite_8[] = {
    "40 31 2",
    "  0",
    "x 1",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    " xxxxxxxxx                    xxxxxxxxx ",
    " xxxxxxxxx                    xxxxxxxxx ",
    " xxxxxxxxx                    xxxxxxxxx ",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    " xxxxxxxxx                    xxxxxxxxx ",
    " xxxxxxxxx                    xxxxxxxxx ",
    " xxxxxxxxx                    xxxxxxxxx ",
    " xxxxxxxxx                    xxxxxxxxx ",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};

static xpm_row_t const sprite_7[] = {
    "40 31 2",
    ". 0",
    "x 1",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    ".......................xxxxxxxxxxxxxxxxx",
    "......................xxxxxxxxxxxxxxxxxx",
    ".....................xxxxxxxxxxxxxxxxxx.",
    "....................xxxxxxxxxxxxxxxxxx..",
    "...................xxxxxxxxxxxxxxxxxx...",
    "..................xxxxxxxxxxxxxxxxxx....",
    ".................xxxxxxxxxxxxxxxxxx.....",
    "................xxxxxxxxxxxxxxxxxx......",
    "...............xxxxxxxxxxxxxxxxxx.......",
    "..............xxxxxxxxxxxxxxxxxx........",
    ".............xxxxxxxxxxxxxxxxxx.........",
    "............xxxxxxxxxxxxxxxxxx..........",
    "...........xxxxxxxxxxxxxxxxxx...........",
    "..........xxxxxxxxxxxxxxxxxx............",
    ".........xxxxxxxxxxxxxxxxxx.............",
    "........xxxxxxxxxxxxxxxxxx..............",
    ".......xxxxxxxxxxxxxxxxxx...............",
    "......xxxxxxxxxxxxxxxxxx................",
    ".....xxxxxxxxxxxxxxxxxx.................",
    "....xxxxxxxxxxxxxxxxxx..................",
    "...xxxxxxxxxxxxxxxxxx...................",
    "..xxxxxxxxxxxxxxxxxx....................",
    ".xxxxxxxxxxxxxxxxxx.....................",
    "xxxxxxxxxxxxxxxxxx......................",
};

static xpm_row_t const sprite_6[] = {
    "40 31 2",
    ". 0",
    "x 1",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};


static xpm_row_t const sprite_5[] = {
    "40 31 2",
    ". 0",
    "x 1",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx.........................",
    "xxxxxxxxxxxxxxx.........................",
    "xxxxxxxxxxxxxxx.........................",
    "xxxxxxxxxxxxxxx.........................",
    "xxxxxxxxxxxxxxx.........................",
    "xxxxxxxxxxxxxxx.........................",
    "xxxxxxxxxxxxxxx.........................",
    "xxxxxxxxxxxxxxx.........................",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};


static xpm_row_t const sprite_4[] = {
    "40 31 2",
    ". 0",
    "x 1",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxx..........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
    ".........................xxxxxxxxxxxxxxx",
};

static xpm_row_t const sprite_3[] = {
    "40 31 2",
    ". 0",
    "x 1",
    "..xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    ".xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.",
    ".xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "..xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "...........................xxxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "...........................xxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..................xxxxxxxxxxxxxxxxxxxxx.",
    ".................xxxxxxxxxxxxxxxxxxxxx..",
    "................xxxxxxxxxxxxxxxxxxxx....",
    ".................xxxxxxxxxxxxxxxxxxxxx..",
    "..................xxxxxxxxxxxxxxxxxxxxx.",
    "..........................xxxxxxxxxxxxxx",
    "...........................xxxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "...........................xxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    ".xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.",
    ".xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..",
    "..xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
};

static xpm_row_t const sprite_2[] = {
    "40 31 2",
    ". 0",
    "x 1",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};


static xpm_row_t const main_menu_sprite_2[] = {
    "40 31 2",
    ". 3",
    "x 8",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "..........................xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxx..........................",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};

static xpm_row_t const sprite_1[] = {
    "40 31 2",
    ". 0",
    "x 1",
    "......................xxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "...............xxxxxxxxxxxxxx...........",
    "...........xxxxxxxxxxxxxxxxxx...........",
    ".......xxxxxxxxx..xxxxxxxxxxx...........",
    "....xxxxxxxx......xxxxxxxxxxx...........",
    ".xxxxxxxxx........xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};


static xpm_row_t const main_menu_sprite_1[] = {
    "40 31 2",
    ". 3",
    "x 8",
    "......................xxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "...............xxxxxxxxxxxxxx...........",
    "...........xxxxxxxxxxxxxxxxxx...........",
    ".......xxxxxxxxx..xxxxxxxxxxx...........",
    "....xxxxxxxx......xxxxxxxxxxx...........",
    ".xxxxxxxxx........xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "..................xxxxxxxxxxx...........",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};

static xpm_row_t const sprite_0[] = {
    "40 31 2",
    "  0",
    "x 1",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};


static xpm_row_t const main_menu_sprite_0[] = {
    "40 31 2",
    "  3",
    "x 8",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxx             xxxxxxxxxxxxxxxxx",
    "xxxxxxxxxx            xxxxxxx xxxxxxxxxx",
    "xxxxxxxxxx           xxxxxxx  xxxxxxxxxx",
    "xxxxxxxxxx           xxxxxxx  xxxxxxxxxx",
    "xxxxxxxxxx          xxxxxxx   xxxxxxxxxx",
    "xxxxxxxxxx         xxxxxxx    xxxxxxxxxx",
    "xxxxxxxxxx         xxxxxxx    xxxxxxxxxx",
    "xxxxxxxxxx        xxxxxxx     xxxxxxxxxx",
    "xxxxxxxxxx       xxxxxxx      xxxxxxxxxx",
    "xxxxxxxxxx       xxxxxxx      xxxxxxxxxx",
    "xxxxxxxxxx       xxxxxxx      xxxxxxxxxx",
    "xxxxxxxxxx       xxxxxxx      xxxxxxxxxx",
    "xxxxxxxxxx       xxxxxxx      xxxxxxxxxx",
    "xxxxxxxxxx       xxxxxxx      xxxxxxxxxx",
    "xxxxxxxxxx      xxxxxxx       xxxxxxxxxx",
    "xxxxxxxxxx     xxxxxxx        xxxxxxxxxx",
    "xxxxxxxxxx    xxxxxxx         xxxxxxxxxx",
    "xxxxxxxxxx   xxxxxxx          xxxxxxxxxx",
    "xxxxxxxxxx  xxxxxxx           xxxxxxxxxx",
    "xxxxxxxxxx xxxxxxx            xxxxxxxxxx",
    "xxxxxxxxxxxxxxxxx             xxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};



static xpm_row_t const main_menu_sprite_A[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "..xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..",
    ".xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
};


static xpm_row_t const main_menu_sprite_B[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..",
    "xxxxxxxxxxx................xxxxxxxxxxx..",
    "xxxxxxxxxxx................xxxxxxxxxxx..",
    "xxxxxxxxxxx................xxxxxxxxxxx..",
    "xxxxxxxxxxx................xxxxxxxxxxx..",
    "xxxxxxxxxxx................xxxxxxxxxxx..",
    "xxxxxxxxxxx................xxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
};

static xpm_row_t const main_menu_sprite_C[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};


static xpm_row_t const main_menu_sprite_E[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};

static xpm_row_t const main_menu_sprite_F[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
    "xxxxxxxxxxxxxxxxx.......................",
};

static xpm_row_t const main_menu_sprite_H[] = {
  "40 31 2",
  ". 3",
  "x 6",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
  "xxxxxxxxxxxxx..............xxxxxxxxxxxxx",
};

static xpm_row_t const main_menu_sprite_I[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...............xxxxxxxxxxx..............",
    "...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
    "...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
};


static xpm_row_t const main_menu_sprite_K[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxxxxxxx.........xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxx.........xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxx........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxx........xxxxxxxxxxxxxx.",
    "xxxxxxxxxxxxxxxxx.......xxxxxxxxxxxxxxx.",
    "xxxxxxxxxxxxxxxxx.......xxxxxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxx.....xxxxxxxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxx....xxxxxxxxxxxxxxxx...",
    "xxxxxxxxxxxxxxxxx...xxxxxxxxxxxxxxxxx...",
    "xxxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxx....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx......",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.......",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.........",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.........",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx........",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.......",
    "xxxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxx......",
    "xxxxxxxxxxxxxxxxx...xxxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxx....xxxxxxxxxxxxxx.....",
    "xxxxxxxxxxxxxxxxx.....xxxxxxxxxxxxxx....",
    "xxxxxxxxxxxxxxxxx.....xxxxxxxxxxxxxxx...",
    "xxxxxxxxxxxxxxxxx......xxxxxxxxxxxxxx...",
    "xxxxxxxxxxxxxxxxx......xxxxxxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxx.......xxxxxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxx.......xxxxxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxx.......xxxxxxxxxxxxxxx.",
    "xxxxxxxxxxxxxxxxx........xxxxxxxxxxxxxx.",
    "xxxxxxxxxxxxxxxxx........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxx.........xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxx.........xxxxxxxxxxxxxx",
};


static xpm_row_t const main_menu_sprite_L[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxx...........................",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};


static xpm_row_t const main_menu_sprite_N[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxxxxxx..........xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx..........xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx..........xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxx........xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxx........xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxx.......xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxx.......xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxx......xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxx.....xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxx.....xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxx....xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx...xxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx....xxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx.....xxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx......xxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx......xxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx.......xxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx.......xxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx........xxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx.........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx.........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx.........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx.........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx.........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxx.........xxxxxxxxxxxxxxx",
};


static xpm_row_t const main_menu_sprite_O[] = {
    "40 31 2",
    "  3",
    "x 6",
    "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxx                  xxxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxxx                  xxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
};


static xpm_row_t const main_menu_sprite_P[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
    "xxxxxxxxxxxx............................",
};


static xpm_row_t const main_menu_sprite_R[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx.................xxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..",
    "xxxxxxxxxxxx...xxxxxxxxxxxx.............",
    "xxxxxxxxxxxx....xxxxxxxxxxxx............",
    "xxxxxxxxxxxx.....xxxxxxxxxxxx...........",
    "xxxxxxxxxxxx......xxxxxxxxxxxx..........",
    "xxxxxxxxxxxx.......xxxxxxxxxxxx.........",
    "xxxxxxxxxxxx........xxxxxxxxxxxx........",
    "xxxxxxxxxxxx.........xxxxxxxxxxxx.......",
    "xxxxxxxxxxxx..........xxxxxxxxxxxx......",
    "xxxxxxxxxxxx...........xxxxxxxxxxxx.....",
    "xxxxxxxxxxxx............xxxxxxxxxxxx....",
    "xxxxxxxxxxxx.............xxxxxxxxxxxx...",
    "xxxxxxxxxxxx..............xxxxxxxxxxxx..",
    "xxxxxxxxxxxx...............xxxxxxxxxxxx.",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
};

static xpm_row_t const main_menu_sprite_S[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxx..................xxxxxxxxxxx",
    "xxxxxxxxxxx.............................",
    "xxxxxxxxxxx.............................",
    "xxxxxxxxxxx.............................",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "xxxxxxxxxxx.................xxxxxxxxxxxx",
    "xxxxxxxxxxx.................xxxxxxxxxxxx",
    "xxxxxxxxxxx.................xxxxxxxxxxxx",
    "xxxxxxxxxxx.................xxxxxxxxxxxx",
    "xxxxxxxxxxx.................xxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};


static xpm_row_t const main_menu_sprite_T[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
    ".............xxxxxxxxxxxxxxx............",
};


static xpm_row_t const main_menu_sprite_U[] = {
    "40 31 2",
    "  3",
    "x 6",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxx                    xxxxxxxxxx",
    "xxxxxxxxxxx                  xxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
};


static xpm_row_t const main_menu_sprite_W[] = {
  "40 31 2",
  "  3",
  "x 6",
  "xxxxxx                            xxxxxx",
  "xxxxxx                            xxxxxx",
  "xxxxxx                            xxxxxx",
  "xxxxxx                            xxxxxx",
  "xxxxxx                            xxxxxx",
  "xxxxxx                            xxxxxx",
  "xxxxxx                            xxxxxx",
  "xxxxxx          xxxxxxxx          xxxxxx",
  "xxxxxx          xxxxxxxx          xxxxxx",
  "xxxxxx          xxxxxxxx          xxxxxx",
  "xxxxxx          xxxxxxxx          xxxxxx",
  "xxxxxx          xxxxxxxx          xxxxxx",
  " xxxxxx         xxxxxxxx         xxxxxx ",
  " xxxxxxx        xxxxxxxx         xxxxxx ",
  " xxxxxxx        xxxxxxxx         xxxxxx ",
  " xxxxxxx        xxxxxxxx         xxxxx  ",
  "  xxxxxx        xxxxxxxx         xxxxx  ",
  "  xxxxxx        xxxxxxxx         xxxxx  ",
  "  xxxxxxx      xxxxxxxxxx       xxxxxx  ",
  "   xxxxxxxx xxxxxxx  xxxxxxx xxxxxxxx   ",
  "    xxxxxxx xxxxxx    xxxxxx xxxxxxx    ",
  "     xxxxxx xxxxx      xxxxx xxxxxx     ",
  "      xxxxxxxxxx        xxxxxxxxxx      ",
  "       xxxxxxxxx        xxxxxxxxxx      ",
  "       xxxxxxxxx        xxxxxxxxxx      ",
  "       xxxxxxxxx        xxxxxxxxxx      ",
  "       xxxxxxxxx        xxxxxxxxxx      ",
  "        xxxxxxxx        xxxxxxxxx       ",
  "         xxxxxx          xxxxxxxx       ",
  "          xxxx            xxxxxx        ",
  "          xxxx             xxxx         ",
};


static xpm_row_t const main_menu_sprite_X[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxxx.............xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxx.............xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxx...........xxxxxxxxxxxxxxx",
    ".xxxxxxxxxxxxx...........xxxxxxxxxxxxxx.",
    ".xxxxxxxxxxxxxx.........xxxxxxxxxxxxxxx.",
    "..xxxxxxxxxxxxx.........xxxxxxxxxxxxxx..",
    "..xxxxxxxxxxxxxx.......xxxxxxxxxxxxxxx..",
    "...xxxxxxxxxxxxx.......xxxxxxxxxxxxxx...",
    "...xxxxxxxxxxxxxx.....xxxxxxxxxxxxxxx...",
    "....xxxxxxxxxxxxx.....xxxxxxxxxxxxxx....",
    "....xxxxxxxxxxxxxx...xxxxxxxxxxxxxxx....",
    ".....xxxxxxxxxxxxx...xxxxxxxxxxxxxx.....",
    ".....xxxxxxxxxxxxxx.xxxxxxxxxxxxxxx.....",
    "......xxxxxxxxxxxxxxxxxxxxxxxxxxxx......",
    "......xxxxxxxxxxxxxxxxxxxxxxxxxxxx......",
    "......xxxxxxxxxxxxxxxxxxxxxxxxxxxx......",
    "......xxxxxxxxxxxxxxxxxxxxxxxxxxxx......",
    ".....xxxxxxxxxxxxxx.xxxxxxxxxxxxxxx.....",
    ".....xxxxxxxxxxxxx...xxxxxxxxxxxxxx.....",
    ".....xxxxxxxxxxxxx...xxxxxxxxxxxxxx.....",
    "....xxxxxxxxxxxxx.....xxxxxxxxxxxxxx....",
    "...xxxxxxxxxxxxxx.....xxxxxxxxxxxxxxx...",
    "...xxxxxxxxxxxxx.......xxxxxxxxxxxxxx...",
    "..xxxxxxxxxxxxxx.......xxxxxxxxxxxxxxx..",
    "..xxxxxxxxxxxxx.........xxxxxxxxxxxxxx..",
    "..xxxxxxxxxxxxx.........xxxxxxxxxxxxxx..",
    ".xxxxxxxxxxxxxx.........xxxxxxxxxxxxxxx.",
    ".xxxxxxxxxxxxx...........xxxxxxxxxxxxxx.",
    "xxxxxxxxxxxxxx...........xxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxx.............xxxxxxxxxxxxxx",
    "xxxxxxxxxxxxx.............xxxxxxxxxxxxxx",
};



static xpm_row_t const main_menu_sprite_Y[] = {
    "40 31 2",
    ". 3",
    "x 6",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxx................xxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "............................xxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
};

//to display countdown during game currently in game.c 
static xpm_row_t const *sprite_number_list[] = {
    sprite_0, sprite_1, sprite_2, sprite_3, sprite_4,
    sprite_5, sprite_6, sprite_7, sprite_8, sprite_9
};

/**@}*/

#endif /* _SPRITES_H */
